#pragma once

#define BLYNK_ENABLE 1
#define BLYNK_TEMPLATE_ID "TMPL2wQIhNDrm"
#define BLYNK_TEMPLATE_NAME "BabyMonitor"
#define BLYNK_AUTH_TOKEN "tsChVa4B12L5LiudcpTjY-SZIsMXjZu6"
#define BLYNK_WIFI_SSID "Sarra"
#define BLYNK_WIFI_PASSWORD "123456789"
#define BLYNK_SERVER_HOST "blynk.cloud"
#define BLYNK_SERVER_PORT 80
#define BLYNK_LOOP_PERIOD_MS 100
#define BLYNK_WIFI_CONNECT_TIMEOUT_MS 15000

#define BLYNK_VPIN_ROOM_TEMP 0
#define BLYNK_VPIN_BODY_TEMP 1
#define BLYNK_VPIN_HEART_RATE 2
#define BLYNK_VPIN_SMOKE 3
#define BLYNK_VPIN_CRY 6
#define BLYNK_VPIN_HUMIDITY 7
#define BLYNK_VPIN_SPO2 9
#define BLYNK_VPIN_ACCEL_X 10
#define BLYNK_VPIN_ACCEL_Y 11
#define BLYNK_VPIN_ACCEL_Z 12
